### PR TITLE
chore(cargo) Update parity-wasm to 0.31.0

### PR DESCRIPTION
**Pull request by Hywan**
Close #11.

### CODE REVIEW

**Comment by fitzgen** [comment]
Care to run `cargo install -f cargo-readme && cargo readme > README.md` to make CI pass? Thanks @Hywan :)

```
	Checking that `cargo readme > README.md` is up to date...
thread 'cargo_readme_up_to_date' panicked at 'Run `cargo readme > README.md` to update README.md', tests/tests.rs:27:9
```

**Comment by fitzgen** [comment]
> Care to run cargo install -f cargo-readme && cargo readme > README.md to make CI pass?

I did this and pushed to master.

**Comment by fitzgen** [comment]
Thanks @Hywan!

**Comment by Hywan** [comment]
:+1:

**Pull request merged**
